In [1]:
import pandas as pd

In [2]:
# Read mhcld-puf-2020-csv.csv 
mh_demo_data = "MH-CLD-2020-DS0001-bndl-data-csv_v1/mhcld-puf-2020-csv.csv"
mh_demo_df = pd.read_csv(mh_demo_data)

In [3]:
# View DataFrame for mhcld-puf-2020-csv.csv
mh_demo_df.head()

,YEAR,AGE,EDUC,ETHNIC,RACE,GENDER,SPHSERVICE,CMPSERVICE,OPISERVICE,RTCSERVICE,...,ODDFLG,PDDFLG,PERSONFLG,SCHIZOFLG,ALCSUBFLG,OTHERDISFLG,STATEFIP,DIVISION,REGION,CASEID
0,2020,14,-9,4,3,1,1,1,1,2,...,0,0,0,1,0,0,1,6,3,20200000001
1,2020,1,2,4,1,1,2,1,2,2,...,0,0,0,0,0,1,1,6,3,20200000002
2,2020,6,-9,4,4,2,2,1,1,2,...,0,0,0,0,0,0,1,6,3,20200000003
3,2020,14,-9,4,3,2,1,1,2,2,...,0,0,0,1,0,0,1,6,3,20200000004
4,2020,13,-9,4,3,2,1,1,1,2,...,0,0,1,1,0,1,1,6,3,20200000005

In [4]:
# Check the datatypes of your columns
mh_demo_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6945521 entries, 0 to 6945520
Data columns (total 40 columns):
 #   Column       Dtype
---  ------       -----
 0   YEAR         int64
 1   AGE          int64
 2   EDUC         int64
 3   ETHNIC       int64
 4   RACE         int64
 5   GENDER       int64
 6   SPHSERVICE   int64
 7   CMPSERVICE   int64
 8   OPISERVICE   int64
 9   RTCSERVICE   int64
 10  IJSSERVICE   int64
 11  MH1          int64
 12  MH2          int64
 13  MH3          int64
 14  SUB          int64
 15  MARSTAT      int64
 16  SMISED       int64
 17  SAP          int64
 18  EMPLOY       int64
 19  DETNLF       int64
 20  VETERAN      int64
 21  LIVARAG      int64
 22  NUMMHS       int64
 23  TRAUSTREFLG  int64
 24  ANXIETYFLG   int64
 25  ADHDFLG      int64
 26  CONDUCTFLG   int64
 27  DELIRDEMFLG  int64
 28  BIPOLARFLG   int64
 29  DEPRESSFLG   int64
 30  ODDFLG       int64
 31  PDDFLG       int64
 32  PERSONFLG    int64
 33  SCHIZOFLG    int64
 34  ALCSUBFLG    int64
 35  OTHERDISFLG  int64
 36  STATEFIP     int64
 37  DIVISION     int64
 38  REGION       int64
 39  CASEID       int64
dtypes: int64(40)
memory usage: 2.1 GB

In [5]:
# Clean up mhcld-puf-2020-csv.csv to only have  State data
# Keep diagnosis flags: Trauma, Anxiety, ADHD, Conduct Disorder,Delirium/Demntia, Bipolar, Depressive Disorder, Oppositional defiant disorder, pervasive development disorder, personality disorder, schizophrenia, alcohol or substance related disorder, other mental disorder
mh_demo_df.drop(columns=['EDUC', 'ETHNIC', 'SPHSERVICE', 'CMPSERVICE', 'OPISERVICE',
                        'RTCSERVICE', 'IJSSERVICE', 'MH1', 'MH2', 'MH3', 'SUB', 'MARSTAT','SMISED', 'SAP', 'EMPLOY',
                        'DETNLF', 'VETERAN', 'LIVARAG', 'NUMMHS'])

,YEAR,AGE,RACE,GENDER,TRAUSTREFLG,ANXIETYFLG,ADHDFLG,CONDUCTFLG,DELIRDEMFLG,BIPOLARFLG,...,ODDFLG,PDDFLG,PERSONFLG,SCHIZOFLG,ALCSUBFLG,OTHERDISFLG,STATEFIP,DIVISION,REGION,CASEID
0,2020,14,3,1,0,0,0,0,1,0,...,0,0,0,1,0,0,1,6,3,20200000001
1,2020,1,1,1,0,1,1,0,0,0,...,0,0,0,0,0,1,1,6,3,20200000002
2,2020,6,4,2,0,0,0,0,0,1,...,0,0,0,0,0,0,1,6,3,20200000003
3,2020,14,3,2,0,0,0,0,0,0,...,0,0,0,1,0,0,1,6,3,20200000004
4,2020,13,3,2,0,0,0,0,0,0,...,0,0,1,1,0,1,1,6,3,20200000005
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6945516,2020,6,-9,1,0,0,0,0,0,0,...,0,0,0,1,0,0,72,0,0,20206945517
6945517,2020,12,6,1,0,0,0,0,0,0,...,0,0,0,1,1,0,72,0,0,20206945518
6945518,2020,4,1,1,0,0,0,0,0,0,...,0,0,0,0,0,1,72,0,0,20206945519
6945519,2020,7,6,1,0,0,0,0,0,0,...,0,0,0,0,1,0,72,0,0,20206945520
6945520,2020,10,5,2,0,0,0,0,0,0,...,0,0,0,1,1,0,72,0,0,20206945521

In [6]:
# Rename DataFrame
clean_mh_demo_data_df=pd.DataFrame(mh_demo_df, columns=['YEAR','CASEID', 'REGION', 'DIVISION', 'STATEFIP', 'AGE', 'RACE', 'GENDER', 'ADHDFLG','ALCSUBFLG', 'ANXIETYFLG', 'BIPOLARFLG', 'CONDUCTFLG', 'DELIRDEMFLG', 'DEPRESSFLG', 'ODDFLG', 'PDDFLG', 'PERSONFLG', 'SCHIZOFLG','TRAUSTREFLG', 'OTHERDISFLG'])
clean_mh_demo_data_df.head()

,YEAR,CASEID,REGION,DIVISION,STATEFIP,AGE,RACE,GENDER,ADHDFLG,ALCSUBFLG,...,BIPOLARFLG,CONDUCTFLG,DELIRDEMFLG,DEPRESSFLG,ODDFLG,PDDFLG,PERSONFLG,SCHIZOFLG,TRAUSTREFLG,OTHERDISFLG
0,2020,20200000001,3,6,1,14,3,1,0,0,...,0,0,1,0,0,0,0,1,0,0
1,2020,20200000002,3,6,1,1,1,1,1,0,...,0,0,0,0,0,0,0,0,0,1
2,2020,20200000003,3,6,1,6,4,2,0,0,...,1,0,0,0,0,0,0,0,0,0
3,2020,20200000004,3,6,1,14,3,2,0,0,...,0,0,0,0,0,0,0,1,0,0
4,2020,20200000005,3,6,1,13,3,2,0,0,...,0,0,0,0,0,0,1,1,0,1

In [7]:
# Save DataFrame as a new file
clean_mh_demo_data_df.to_csv('MentalHealth_DemoData.js')

In [8]:
# Read MentalHealth_StateData.csv 
clean_mh_demo_data = "MentalHealth_DemoData.js"
clean_mh_demo_df = pd.read_csv(clean_mh_demo_data)

In [9]:
# Convert columns RACE, STATEIP, DIVISION and REGION from int64 to string
clean_mh_demo_data_df['STATEFIP']=clean_mh_demo_data_df['STATEFIP'].map(str)
clean_mh_demo_data_df['DIVISION']=clean_mh_demo_data_df['DIVISION'].map(str)
clean_mh_demo_data_df['REGION']=clean_mh_demo_data_df['REGION'].map(str)

In [10]:
# Convert STATEFIP from numbers to States and Territory names
clean_mh_demo_data_df['STATEFIP']=clean_mh_demo_data_df['STATEFIP'].replace(['1'], 'Alabama')
clean_mh_demo_data_df['STATEFIP']=clean_mh_demo_data_df['STATEFIP'].replace(['2'], 'Alaska')
clean_mh_demo_data_df['STATEFIP']=clean_mh_demo_data_df['STATEFIP'].replace(['4'], 'Arizona')
clean_mh_demo_data_df['STATEFIP']=clean_mh_demo_data_df['STATEFIP'].replace(['5'], 'Arkansas')
clean_mh_demo_data_df['STATEFIP']=clean_mh_demo_data_df['STATEFIP'].replace(['6'], 'California')
clean_mh_demo_data_df['STATEFIP']=clean_mh_demo_data_df['STATEFIP'].replace(['8'], 'Colorado')
clean_mh_demo_data_df['STATEFIP']=clean_mh_demo_data_df['STATEFIP'].replace(['9'], 'Connecticut')
clean_mh_demo_data_df['STATEFIP']=clean_mh_demo_data_df['STATEFIP'].replace(['10'], 'Delaware')
clean_mh_demo_data_df['STATEFIP']=clean_mh_demo_data_df['STATEFIP'].replace(['11'], 'District of Columbia')
clean_mh_demo_data_df['STATEFIP']=clean_mh_demo_data_df['STATEFIP'].replace(['12'], 'Florida')
clean_mh_demo_data_df['STATEFIP']=clean_mh_demo_data_df['STATEFIP'].replace(['13'], 'Georgia')
clean_mh_demo_data_df['STATEFIP']=clean_mh_demo_data_df['STATEFIP'].replace(['15'], 'Hawaii')
clean_mh_demo_data_df['STATEFIP']=clean_mh_demo_data_df['STATEFIP'].replace(['16'], 'Idaho')
clean_mh_demo_data_df['STATEFIP']=clean_mh_demo_data_df['STATEFIP'].replace(['17'], 'Illinois')
clean_mh_demo_data_df['STATEFIP']=clean_mh_demo_data_df['STATEFIP'].replace(['18'], 'Indiana')
clean_mh_demo_data_df['STATEFIP']=clean_mh_demo_data_df['STATEFIP'].replace(['19'], 'Iowa')
clean_mh_demo_data_df['STATEFIP']=clean_mh_demo_data_df['STATEFIP'].replace(['20'], 'Kansas')
clean_mh_demo_data_df['STATEFIP']=clean_mh_demo_data_df['STATEFIP'].replace(['21'], 'Kentucky')
clean_mh_demo_data_df['STATEFIP']=clean_mh_demo_data_df['STATEFIP'].replace(['22'], 'Lousisiana')
clean_mh_demo_data_df['STATEFIP']=clean_mh_demo_data_df['STATEFIP'].replace(['25'], 'Massachusetts')
clean_mh_demo_data_df['STATEFIP']=clean_mh_demo_data_df['STATEFIP'].replace(['26'], 'Michigan')
clean_mh_demo_data_df['STATEFIP']=clean_mh_demo_data_df['STATEFIP'].replace(['27'], 'Minnesota')
clean_mh_demo_data_df['STATEFIP']=clean_mh_demo_data_df['STATEFIP'].replace(['28'], 'Mississippi')
clean_mh_demo_data_df['STATEFIP']=clean_mh_demo_data_df['STATEFIP'].replace(['29'], 'Missouri')
clean_mh_demo_data_df['STATEFIP']=clean_mh_demo_data_df['STATEFIP'].replace(['30'], 'Montana')
clean_mh_demo_data_df['STATEFIP']=clean_mh_demo_data_df['STATEFIP'].replace(['31'], 'Nebraska')
clean_mh_demo_data_df['STATEFIP']=clean_mh_demo_data_df['STATEFIP'].replace(['32'], 'Nevada')
clean_mh_demo_data_df['STATEFIP']=clean_mh_demo_data_df['STATEFIP'].replace(['34'], 'New Jersey')
clean_mh_demo_data_df['STATEFIP']=clean_mh_demo_data_df['STATEFIP'].replace(['35'], 'New Mexico')
clean_mh_demo_data_df['STATEFIP']=clean_mh_demo_data_df['STATEFIP'].replace(['36'], 'New York')
clean_mh_demo_data_df['STATEFIP']=clean_mh_demo_data_df['STATEFIP'].replace(['37'], 'North Carolina')
clean_mh_demo_data_df['STATEFIP']=clean_mh_demo_data_df['STATEFIP'].replace(['38'], 'North Dakota')
clean_mh_demo_data_df['STATEFIP']=clean_mh_demo_data_df['STATEFIP'].replace(['39'], 'Ohio')
clean_mh_demo_data_df['STATEFIP']=clean_mh_demo_data_df['STATEFIP'].replace(['40'], 'Oklahoma')
clean_mh_demo_data_df['STATEFIP']=clean_mh_demo_data_df['STATEFIP'].replace(['41'], 'Oregon')
clean_mh_demo_data_df['STATEFIP']=clean_mh_demo_data_df['STATEFIP'].replace(['42'], 'Pennsylvania')
clean_mh_demo_data_df['STATEFIP']=clean_mh_demo_data_df['STATEFIP'].replace(['44'], 'Rhode Island')
clean_mh_demo_data_df['STATEFIP']=clean_mh_demo_data_df['STATEFIP'].replace(['45'], 'South Carolina')
clean_mh_demo_data_df['STATEFIP']=clean_mh_demo_data_df['STATEFIP'].replace(['46'], 'South Dakota')
clean_mh_demo_data_df['STATEFIP']=clean_mh_demo_data_df['STATEFIP'].replace(['47'], 'Tennessee')
clean_mh_demo_data_df['STATEFIP']=clean_mh_demo_data_df['STATEFIP'].replace(['48'], 'Texas')
clean_mh_demo_data_df['STATEFIP']=clean_mh_demo_data_df['STATEFIP'].replace(['49'], 'Utah')
clean_mh_demo_data_df['STATEFIP']=clean_mh_demo_data_df['STATEFIP'].replace(['50'], 'Vermont')
clean_mh_demo_data_df['STATEFIP']=clean_mh_demo_data_df['STATEFIP'].replace(['51'], 'Virginia')
clean_mh_demo_data_df['STATEFIP']=clean_mh_demo_data_df['STATEFIP'].replace(['53'], 'Washington')
clean_mh_demo_data_df['STATEFIP']=clean_mh_demo_data_df['STATEFIP'].replace(['55'], 'Wisconsin')
clean_mh_demo_data_df['STATEFIP']=clean_mh_demo_data_df['STATEFIP'].replace(['56'], 'Wyoming')
clean_mh_demo_data_df['STATEFIP']=clean_mh_demo_data_df['STATEFIP'].replace(['72'], 'Puerto Rico')
clean_mh_demo_data_df['STATEFIP']=clean_mh_demo_data_df['STATEFIP'].replace(['99'], 'Other Jurisdictions')

In [11]:
# View DataFram mh_demo_data.df
clean_mh_demo_data_df

,YEAR,CASEID,REGION,DIVISION,STATEFIP,AGE,RACE,GENDER,ADHDFLG,ALCSUBFLG,...,BIPOLARFLG,CONDUCTFLG,DELIRDEMFLG,DEPRESSFLG,ODDFLG,PDDFLG,PERSONFLG,SCHIZOFLG,TRAUSTREFLG,OTHERDISFLG
0,2020,20200000001,3,6,Alabama,14,3,1,0,0,...,0,0,1,0,0,0,0,1,0,0
1,2020,20200000002,3,6,Alabama,1,1,1,1,0,...,0,0,0,0,0,0,0,0,0,1
2,2020,20200000003,3,6,Alabama,6,4,2,0,0,...,1,0,0,0,0,0,0,0,0,0
3,2020,20200000004,3,6,Alabama,14,3,2,0,0,...,0,0,0,0,0,0,0,1,0,0
4,2020,20200000005,3,6,Alabama,13,3,2,0,0,...,0,0,0,0,0,0,1,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6945516,2020,20206945517,0,0,Puerto Rico,6,-9,1,0,0,...,0,0,0,0,0,0,0,1,0,0
6945517,2020,20206945518,0,0,Puerto Rico,12,6,1,0,1,...,0,0,0,0,0,0,0,1,0,0
6945518,2020,20206945519,0,0,Puerto Rico,4,1,1,0,0,...,0,0,0,1,0,0,0,0,0,1
6945519,2020,20206945520,0,0,Puerto Rico,7,6,1,0,1,...,0,0,0,0,0,0,0,0,0,0
6945520,2020,20206945521,0,0,Puerto Rico,10,5,2,0,1,...,0,0,0,0,0,0,0,1,0,0

In [12]:
# Convert columns RACE int64 to string
clean_mh_demo_data_df['RACE']=clean_mh_demo_data_df['RACE'].map(str)

In [13]:
# Convert Race from numbers to RACE label names
clean_mh_demo_data_df['RACE']=clean_mh_demo_data_df['RACE'].replace(['1'], 'American Indian/Alaska Native')
clean_mh_demo_data_df['RACE']=clean_mh_demo_data_df['RACE'].replace(['2'], 'Asian')
clean_mh_demo_data_df['RACE']=clean_mh_demo_data_df['RACE'].replace(['3'], 'Black or African American')
clean_mh_demo_data_df['RACE']=clean_mh_demo_data_df['RACE'].replace(['4'], 'Native Hawaiian or Other Pacific Islander')
clean_mh_demo_data_df['RACE']=clean_mh_demo_data_df['RACE'].replace(['5'], 'White')
clean_mh_demo_data_df['RACE']=clean_mh_demo_data_df['RACE'].replace(['6'], 'Some other race alone/two or more races')
clean_mh_demo_data_df['RACE']=clean_mh_demo_data_df['RACE'].replace(['-9'], 'Missing/unknown/not collected/invalid')

In [14]:
# View DataFram mh_demo_data.df
clean_mh_demo_data_df

,YEAR,CASEID,REGION,DIVISION,STATEFIP,AGE,RACE,GENDER,ADHDFLG,ALCSUBFLG,...,BIPOLARFLG,CONDUCTFLG,DELIRDEMFLG,DEPRESSFLG,ODDFLG,PDDFLG,PERSONFLG,SCHIZOFLG,TRAUSTREFLG,OTHERDISFLG
0,2020,20200000001,3,6,Alabama,14,Black or African American,1,0,0,...,0,0,1,0,0,0,0,1,0,0
1,2020,20200000002,3,6,Alabama,1,American Indian/Alaska Native,1,1,0,...,0,0,0,0,0,0,0,0,0,1
2,2020,20200000003,3,6,Alabama,6,Native Hawaiian or Other Pacific Islander,2,0,0,...,1,0,0,0,0,0,0,0,0,0
3,2020,20200000004,3,6,Alabama,14,Black or African American,2,0,0,...,0,0,0,0,0,0,0,1,0,0
4,2020,20200000005,3,6,Alabama,13,Black or African American,2,0,0,...,0,0,0,0,0,0,1,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6945516,2020,20206945517,0,0,Puerto Rico,6,Missing/unknown/not collected/invalid,1,0,0,...,0,0,0,0,0,0,0,1,0,0
6945517,2020,20206945518,0,0,Puerto Rico,12,Some other race alone/two or more races,1,0,1,...,0,0,0,0,0,0,0,1,0,0
6945518,2020,20206945519,0,0,Puerto Rico,4,American Indian/Alaska Native,1,0,0,...,0,0,0,1,0,0,0,0,0,1
6945519,2020,20206945520,0,0,Puerto Rico,7,Some other race alone/two or more races,1,0,1,...,0,0,0,0,0,0,0,0,0,0
6945520,2020,20206945521,0,0,Puerto Rico,10,White,2,0,1,...,0,0,0,0,0,0,0,1,0,0

In [15]:
# Convert DIVISION from numbers to names
# Convert STATEFIP from numbers to States and Territory names
clean_mh_demo_data_df['DIVISION']=clean_mh_demo_data_df['DIVISION'].replace(['0'], 'Other Jurisdictions')
clean_mh_demo_data_df['DIVISION']=clean_mh_demo_data_df['DIVISION'].replace(['1'], 'New England')
clean_mh_demo_data_df['DIVISION']=clean_mh_demo_data_df['DIVISION'].replace(['2'], 'Middle Atlantic')
clean_mh_demo_data_df['DIVISION']=clean_mh_demo_data_df['DIVISION'].replace(['3'], 'East North Central')
clean_mh_demo_data_df['DIVISION']=clean_mh_demo_data_df['DIVISION'].replace(['4'], 'West North Central')
clean_mh_demo_data_df['DIVISION']=clean_mh_demo_data_df['DIVISION'].replace(['5'], 'South Atlantic')
clean_mh_demo_data_df['DIVISION']=clean_mh_demo_data_df['DIVISION'].replace(['6'], 'East South Central')
clean_mh_demo_data_df['DIVISION']=clean_mh_demo_data_df['DIVISION'].replace(['7'], 'West South Central')
clean_mh_demo_data_df['DIVISION']=clean_mh_demo_data_df['DIVISION'].replace(['8'], 'Mountain')
clean_mh_demo_data_df['DIVISION']=clean_mh_demo_data_df['DIVISION'].replace(['9'], 'Pacific')

In [16]:
# View DataFram mh_state_data.df
clean_mh_demo_data_df

,YEAR,CASEID,REGION,DIVISION,STATEFIP,AGE,RACE,GENDER,ADHDFLG,ALCSUBFLG,...,BIPOLARFLG,CONDUCTFLG,DELIRDEMFLG,DEPRESSFLG,ODDFLG,PDDFLG,PERSONFLG,SCHIZOFLG,TRAUSTREFLG,OTHERDISFLG
0,2020,20200000001,3,East South Central,Alabama,14,Black or African American,1,0,0,...,0,0,1,0,0,0,0,1,0,0
1,2020,20200000002,3,East South Central,Alabama,1,American Indian/Alaska Native,1,1,0,...,0,0,0,0,0,0,0,0,0,1
2,2020,20200000003,3,East South Central,Alabama,6,Native Hawaiian or Other Pacific Islander,2,0,0,...,1,0,0,0,0,0,0,0,0,0
3,2020,20200000004,3,East South Central,Alabama,14,Black or African American,2,0,0,...,0,0,0,0,0,0,0,1,0,0
4,2020,20200000005,3,East South Central,Alabama,13,Black or African American,2,0,0,...,0,0,0,0,0,0,1,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6945516,2020,20206945517,0,Other Jurisdictions,Puerto Rico,6,Missing/unknown/not collected/invalid,1,0,0,...,0,0,0,0,0,0,0,1,0,0
6945517,2020,20206945518,0,Other Jurisdictions,Puerto Rico,12,Some other race alone/two or more races,1,0,1,...,0,0,0,0,0,0,0,1,0,0
6945518,2020,20206945519,0,Other Jurisdictions,Puerto Rico,4,American Indian/Alaska Native,1,0,0,...,0,0,0,1,0,0,0,0,0,1
6945519,2020,20206945520,0,Other Jurisdictions,Puerto Rico,7,Some other race alone/two or more races,1,0,1,...,0,0,0,0,0,0,0,0,0,0
6945520,2020,20206945521,0,Other Jurisdictions,Puerto Rico,10,White,2,0,1,...,0,0,0,0,0,0,0,1,0,0

In [36]:
# Convert REGION from numbers to names
clean_mh_demo_data_df['REGION']=clean_mh_demo_data_df['REGION'].replace(['0'], 'Other Jurisdictions')
clean_mh_demo_data_df['REGION']=clean_mh_demo_data_df['REGION'].replace(['1'], 'Northeast')
clean_mh_demo_data_df['REGION']=clean_mh_demo_data_df['REGION'].replace(['2'], 'Midwest')
clean_mh_demo_data_df['REGION']=clean_mh_demo_data_df['REGION'].replace(['3'], 'South')
clean_mh_demo_data_df['REGION']=clean_mh_demo_data_df['REGION'].replace(['4'], 'West')

In [30]:
# View DataFram mh_state_data.df
clean_mh_demo_data_df

,YEAR,CASEID,REGION,DIVISION,STATEFIP,AGE,RACE,GENDER,ADHDFLG,ALCSUBFLG,...,CONDUCTFLG,DELIRDEMFLG,DEPRESSFLG,ODDFLG,PDDFLG,PERSONFLG,SCHIZOFLG,TRAUSTREFLG,OTHERDISFLG,DIAGNOSIS
0,2020,20200000001,South,East South Central,Alabama,14,Black or African American,Male,0,0,...,0,1,0,0,0,0,1,0,0,NaN
1,2020,20200000002,South,East South Central,Alabama,1,American Indian/Alaska Native,Male,1,0,...,0,0,0,0,0,0,0,0,1,NaN
2,2020,20200000003,South,East South Central,Alabama,6,Native Hawaiian or Other Pacific Islander,Female,0,0,...,0,0,0,0,0,0,0,0,0,NaN
3,2020,20200000004,South,East South Central,Alabama,14,Black or African American,Female,0,0,...,0,0,0,0,0,0,1,0,0,NaN
4,2020,20200000005,South,East South Central,Alabama,13,Black or African American,Female,0,0,...,0,0,0,0,0,1,1,0,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6945516,2020,20206945517,Other Jurisdictions,Other Jurisdictions,Puerto Rico,6,Missing/unknown/not collected/invalid,Male,0,0,...,0,0,0,0,0,0,1,0,0,NaN
6945517,2020,20206945518,Other Jurisdictions,Other Jurisdictions,Puerto Rico,12,Some other race alone/two or more races,Male,0,1,...,0,0,0,0,0,0,1,0,0,NaN
6945518,2020,20206945519,Other Jurisdictions,Other Jurisdictions,Puerto Rico,4,American Indian/Alaska Native,Male,0,0,...,0,0,1,0,0,0,0,0,1,NaN
6945519,2020,20206945520,Other Jurisdictions,Other Jurisdictions,Puerto Rico,7,Some other race alone/two or more races,Male,0,1,...,0,0,0,0,0,0,0,0,0,NaN
6945520,2020,20206945521,Other Jurisdictions,Other Jurisdictions,Puerto Rico,10,White,Female,0,1,...,0,0,0,0,0,0,1,0,0,NaN

In [31]:
print(clean_mh_demo_data_df['GENDER'].unique())

['Male' 'Female' 'Unknown']

In [32]:
# change data type for GENDER from int64 to text string
clean_mh_demo_data_df['GENDER']=clean_mh_demo_data_df['GENDER'].astype(str)

In [33]:
# Convert Gender from numbers to Gender label names
clean_mh_demo_data_df['GENDER']=clean_mh_demo_data_df['GENDER'].replace(['1'], 'Male')
clean_mh_demo_data_df['GENDER']=clean_mh_demo_data_df['GENDER'].replace(['2'], 'Female')
clean_mh_demo_data_df['GENDER']=clean_mh_demo_data_df['GENDER'].replace(['-9'], 'Unknown')

In [34]:
clean_mh_demo_data_df

,YEAR,CASEID,REGION,DIVISION,STATEFIP,AGE,RACE,GENDER,ADHDFLG,ALCSUBFLG,...,CONDUCTFLG,DELIRDEMFLG,DEPRESSFLG,ODDFLG,PDDFLG,PERSONFLG,SCHIZOFLG,TRAUSTREFLG,OTHERDISFLG,DIAGNOSIS
0,2020,20200000001,South,East South Central,Alabama,14,Black or African American,Male,0,0,...,0,1,0,0,0,0,1,0,0,NaN
1,2020,20200000002,South,East South Central,Alabama,1,American Indian/Alaska Native,Male,1,0,...,0,0,0,0,0,0,0,0,1,NaN
2,2020,20200000003,South,East South Central,Alabama,6,Native Hawaiian or Other Pacific Islander,Female,0,0,...,0,0,0,0,0,0,0,0,0,NaN
3,2020,20200000004,South,East South Central,Alabama,14,Black or African American,Female,0,0,...,0,0,0,0,0,0,1,0,0,NaN
4,2020,20200000005,South,East South Central,Alabama,13,Black or African American,Female,0,0,...,0,0,0,0,0,1,1,0,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6945516,2020,20206945517,Other Jurisdictions,Other Jurisdictions,Puerto Rico,6,Missing/unknown/not collected/invalid,Male,0,0,...,0,0,0,0,0,0,1,0,0,NaN
6945517,2020,20206945518,Other Jurisdictions,Other Jurisdictions,Puerto Rico,12,Some other race alone/two or more races,Male,0,1,...,0,0,0,0,0,0,1,0,0,NaN
6945518,2020,20206945519,Other Jurisdictions,Other Jurisdictions,Puerto Rico,4,American Indian/Alaska Native,Male,0,0,...,0,0,1,0,0,0,0,0,1,NaN
6945519,2020,20206945520,Other Jurisdictions,Other Jurisdictions,Puerto Rico,7,Some other race alone/two or more races,Male,0,1,...,0,0,0,0,0,0,0,0,0,NaN
6945520,2020,20206945521,Other Jurisdictions,Other Jurisdictions,Puerto Rico,10,White,Female,0,1,...,0,0,0,0,0,0,1,0,0,NaN

In [37]:
# adding a column called diagnosis which will populate the name of the diagnosis found in each record
#create an empty list to hold name of diagnosis 

diagnosis_list = []

for i, row in clean_mh_demo_data_df.iterrows():
    diagnosis_list = []
    if row['ADHDFLG'] == 1:
        diagnosis_list.append('Attention deficit/hyperactivity disorder (ADHD)')
    if row['ALCSUBFLG'] == 1:
        diagnosis_list.append('Alcohol or substance use disorders')
    if row['ANXIETYFLG'] == 1:
        diagnosis_list.append('Anxiety disorders')
    if row['BIPOLARFLG'] == 1:
        diagnosis_list.append('Bipolar disorders')
    if row['CONDUCTFLG'] == 1:
        diagnosis_list.append('Conduct disorders')
    if row['DELIRDEMFLG'] == 1:
        diagnosis_list.append('Delirium/dementia')     
    if row['DEPRESSFLG'] == 1:
        diagnosis_list.append('Depressive disorders')
    if row['ODDFLG'] == 1:
        diagnosis_list.append('Oppositional defiant disorders')
    if row['PDDFLG'] == 1:
        diagnosis_list.append('Pervasive developmental disorder')
    if row['PERSONFLG'] == 1:
        diagnosis_list.append('Personality disorders')
    if row['SCHIZOFLG'] == 1:
        diagnosis_list.append('Schizophrenia or other psychotic disorders')
    if row['TRAUSTREFLG'] == 1:
        diagnosis_list.append('Trauma- and stressor-related disorders')
    if row['OTHERDISFLG'] == 1:
        diagnosis_list.append('Other disorders/conditions') 
    if not diagnosis_list:
        diagnosis_list.append("Information unavailable")
        
    diagnosis_list.append(diagnosis_list)

In [28]:
clean_mh_demo_data_df.at[i, "DIAGNOSIS"] = diagnosis_list

C:\Users\on080\anaconda3\lib\site-packages\pandas\core\dtypes\missing.py:550: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  val = np.array(val, copy=False)
C:\Users\on080\anaconda3\lib\site-packages\numpy\core\fromnumeric.py:3162: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  return asarray(a).ndim

ValueError: Must have equal len keys and value when setting with an iterable

In [38]:
clean_mh_demo_data_df

,YEAR,CASEID,REGION,DIVISION,STATEFIP,AGE,RACE,GENDER,ADHDFLG,ALCSUBFLG,...,CONDUCTFLG,DELIRDEMFLG,DEPRESSFLG,ODDFLG,PDDFLG,PERSONFLG,SCHIZOFLG,TRAUSTREFLG,OTHERDISFLG,DIAGNOSIS
0,2020,20200000001,South,East South Central,Alabama,14,Black or African American,Male,0,0,...,0,1,0,0,0,0,1,0,0,NaN
1,2020,20200000002,South,East South Central,Alabama,1,American Indian/Alaska Native,Male,1,0,...,0,0,0,0,0,0,0,0,1,NaN
2,2020,20200000003,South,East South Central,Alabama,6,Native Hawaiian or Other Pacific Islander,Female,0,0,...,0,0,0,0,0,0,0,0,0,NaN
3,2020,20200000004,South,East South Central,Alabama,14,Black or African American,Female,0,0,...,0,0,0,0,0,0,1,0,0,NaN
4,2020,20200000005,South,East South Central,Alabama,13,Black or African American,Female,0,0,...,0,0,0,0,0,1,1,0,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6945516,2020,20206945517,Other Jurisdictions,Other Jurisdictions,Puerto Rico,6,Missing/unknown/not collected/invalid,Male,0,0,...,0,0,0,0,0,0,1,0,0,NaN
6945517,2020,20206945518,Other Jurisdictions,Other Jurisdictions,Puerto Rico,12,Some other race alone/two or more races,Male,0,1,...,0,0,0,0,0,0,1,0,0,NaN
6945518,2020,20206945519,Other Jurisdictions,Other Jurisdictions,Puerto Rico,4,American Indian/Alaska Native,Male,0,0,...,0,0,1,0,0,0,0,0,1,NaN
6945519,2020,20206945520,Other Jurisdictions,Other Jurisdictions,Puerto Rico,7,Some other race alone/two or more races,Male,0,1,...,0,0,0,0,0,0,0,0,0,NaN
6945520,2020,20206945521,Other Jurisdictions,Other Jurisdictions,Puerto Rico,10,White,Female,0,1,...,0,0,0,0,0,0,1,0,0,NaN

In [ ]:
diagnosis_lookup = [
    'Attention deficit/hyperactivity disorder (ADHD)',
    'Alcohol or substance use disorders',
    'Anxiety disorders',
    'Bipolar disorders',
    'Conduct disorders',
    'Delirium/dementia',
    'Depressive disorders',
    'Oppositional defiant disorders',
    '9 Pervasive developmental disorder',
    'Personality disorders',
    'Schizophrenia or other psychotic disorders',
    'Trauma- and stressor-related disorders',
    'Other disorders/conditions'
]

In [ ]:
def transform_function(row):
    if isinstance(row, list):
        # If the input is a list, access the values using their indices
        diagnosis_names = []  # Initialize an empty list to store the diagnosis names
        
        # Iterate through each diagnosis flag
        for i in range(9, 22):  # The diagnosis flags are in the 9th to 22 indices of the row
            if row[i] == 1:  # If the flag is set to 1, add the corresponding diagnosis name to the list
                diagnosis_names.append(diagnosis_lookup[i-9])
        # If the input is a list, access the values using their indices
        return {
        "YEAR": row[1],
        "CASEID": row[2],
        "REGION": row[3],
        "DIVISION": row[4],
        "STATEFIP": row[5],
        "AGE": row[6],
        "RACE": row[7],
        "GENDER": row[8],
        "ADHDFLG": row[9],
        "ALCSUBFLG": row[10],
        "ANXIETYFLG": row[11],
        "BIPOLARFLG": row[12],
        "CONDUCTFLG": row[13],
        "DELIRDEMFLG": row[14],
        "DEPRESSFLG": row[15],
        "ODDFLG": row[16],
        "PDDFLG": row[17],
        "PERSONFLG": row[18],
        "SCHIZOFLG": row[19],
        "TRAUSTREFLG": row[20],
        "OTHERDISFLG": row[21],
            # Add the list of diagnosis names to the dictionary
        "DIAGNOSIS": row[22]  
        }

In [ ]:
clean_mh_demo_data_df

In [ ]:
#clean_mh_demo_data_df = clean_mh_demo_data_df.apply(transform_function, axis=1)

In [ ]:
clean_mh_demo_data_df

In [ ]:
# Save DataFrame as a new file
#clean_mh_demo_data_df.to_csv('MentalHealth_2020DemoData.js')

In [ ]:
# Save DataFrame as a new file
#clean_mh_demo_data_df.to_csv('MentalHealth_2020DemoData.csv')